name: Build banners index
on:
  push:
    branches: [ main, master ]
    paths:
      - 'json/banners/*.json'
      - '.github/workflows/build-banners-index.yml'
  workflow_dispatch:

jobs:
  build-index:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Ensure folder exists
        run: mkdir -p json/banners

      - name: Generate json/banners/index.json
        shell: bash
        run: |
          set -euo pipefail
          shopt -s nullglob
          files=(json/banners/*.json)
          # remove o próprio index.json da lista se já existir
          out="json/banners/index.json"
          tmp="$(mktemp)"
          : > "$tmp"
          declare -a arr=()
          for f in "${files[@]}"; do
            base="$(basename "$f")"
            if [[ "$base" == "index.json" ]]; then
              continue
            fi
            arr+=("$base")
          done
          # Ordena alfabeticamente
          printf '%s\n' "${arr[@]}" | jq -R -s -c 'split("\n") | map(select(length>0)) | sort' | jq . > "$out"
          echo "index.json:"
          cat "$out"

      - name: Commit & push if changed
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            git config user.name  "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add json/banners/index.json
            git commit -m "chore: update banners index.json"
            git push
          else
            echo "No changes to commit."
          fi
      - name: Print hint
        run: |
          echo "Pronto! Cada arquivo em json/banners/*.json é listado no index.json automaticamente."
